import type { Agent, Customer, Ticket } from "@/lib/types";

export const agents: Agent[] = [
  { id: "agent-1", name: "Alex Johnson", avatarUrl: "/avatars/01.png" },
  { id: "agent-2", name: "Maria Garcia", avatarUrl: "/avatars/02.png" },
  { id: "agent-3", name: "James Smith", avatarUrl: "/avatars/03.png" },
];

export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Askar Aituov",
    email: "askar.aituov@example.com",
    phone: "+1-202-555-0178",
    avatarUrl: "/avatars/04.png",
    orderIds: ["#99877", "#99878", "#99879"],
    lastInteraction: "2024-08-22T14:30:00Z",
    notes: [
      {
        id: "note-1",
        text: "Customer is a VIP. Prioritize their requests.",
        createdAt: "2024-08-20T10:00:00Z",
      },
    ],
  },
  {
    id: "cust-2",
    name: "Emily Carter",
    email: "emily.carter@example.com",
    phone: "+1-310-555-0188",
    avatarUrl: "/avatars/05.png",
    orderIds: ["#10321", "#10322"],
    lastInteraction: "2024-08-23T10:15:00Z",
    notes: [],
  },
  {
    id: "cust-3",
    name: "Benjamin Lee",
    email: "ben.lee@example.com",
    phone: "+1-415-555-0199",
    avatarUrl: "/avatars/06.png",
    orderIds: ["#45001"],
    lastInteraction: "2024-08-21T09:00:00Z",
    notes: [],
  },
];

export const tickets: Ticket[] = [
  {
    id: "ticket-1",
    subject: "Issue with my order #99877",
    customerId: "cust-1",
    agentId: "agent-1",
    channel: "email",
    status: "open",
    priority: "high",
    unread: true,
    createdAt: "2024-08-24T10:00:00Z",
    dueDate: "2024-08-25T10:00:00Z",
    messages: [
      {
        id: "msg-1-1",
        author: "customer",
        authorName: "Askar Aituov",
        authorAvatarUrl: "/avatars/04.png",
        text: "Hi, I'm having an issue with my recent order #99877. The tracking shows it as delivered, but I haven't received it.",
        timestamp: "2024-08-24T10:00:00Z",
        isInternal: false,
      },
      {
        id: "msg-1-2",
        author: "agent",
        authorName: "Alex Johnson",
        authorAvatarUrl: "/avatars/01.png",
        text: "Hi Askar, I'm sorry to hear about the trouble with your order. Let me look into the tracking details for you right away.",
        timestamp: "2024-08-24T10:05:00Z",
        isInternal: false,
      },
       {
        id: "msg-1-3",
        author: "agent",
        authorName: "Alex Johnson",
        authorAvatarUrl: "/avatars/01.png",
        text: "Double-checking with logistics. This seems to be a recurring issue in the same delivery area. Need to flag for review.",
        timestamp: "2024-08-24T10:07:00Z",
        isInternal: true,
      },
    ],
  },
  {
    id: "ticket-2",
    subject: "Question about product specifications",
    customerId: "cust-2",
    agentId: "agent-2",
    channel: "chat",
    status: "open",
    priority: "medium",
    unread: true,
    createdAt: "2024-08-24T11:30:00Z",
    messages: [
      {
        id: "msg-2-1",
        author: "customer",
        authorName: "Emily Carter",
        authorAvatarUrl: "/avatars/05.png",
        text: "Hey, can you tell me if the 'Sky-View Drone' has a 4K camera?",
        timestamp: "2024-08-24T11:30:00Z",
        isInternal: false,
      },
    ],
  },
  {
    id: "ticket-3",
    subject: "Call regarding a return",
    customerId: "cust-3",
    agentId: "agent-1",
    channel: "phone",
    status: "pending",
    priority: "low",
    unread: false,
    createdAt: "2024-08-23T16:45:00Z",
    messages: [
      {
        id: "msg-3-1",
        author: "system",
        authorName: "System",
        authorAvatarUrl: "/avatars/system.png",
        text: "Phone log: Customer Benjamin Lee called regarding a return for order #45001. Agent Alex Johnson created this ticket to follow up with the returns department.",
        timestamp: "2024-08-23T16:45:00Z",
        isInternal: false,
      },
    ],
  },
  {
    id: "ticket-4",
    subject: "My discount code isn't working",
    customerId: "cust-1",
    agentId: "agent-2",
    channel: "chat",
    status: "resolved",
    priority: "medium",
    unread: false,
    createdAt: "2024-08-22T14:30:00Z",
    messages: [
      {
        id: "msg-4-1",
        author: "customer",
        authorName: "Askar Aituov",
        authorAvatarUrl: "/avatars/04.png",
        text: "The 'SUMMER20' code doesn't apply at checkout.",
        timestamp: "2024-08-22T14:30:00Z",
        isInternal: false,
      },
      {
        id: "msg-4-2",
        author: "agent",
        authorName: "Maria Garcia",
        authorAvatarUrl: "/avatars/02.png",
        text: "It seems that code is expired. Here is a new one for you: 'WELCOME25'.",
        timestamp: "2024-08-22T14:32:00Z",
        isInternal: false,
      },
       {
        id: "msg-4-3",
        author: "customer",
        authorName: "Askar Aituov",
        authorAvatarUrl: "/avatars/04.png",
        text: "Great, that worked! Thanks!",
        timestamp: "2024-08-22T14:33:00Z",
        isInternal: false,
      },
    ],
  },
  {
    id: "ticket-5",
    subject: "Re: Your order has shipped!",
    customerId: "cust-2",
    agentId: "agent-3",
    channel: "email",
    status: "open",
    priority: "low",
    unread: false,
    createdAt: "2024-08-24T09:15:00Z",
    messages: [
        {
            id: "msg-5-1",
            author: "customer",
            authorName: "Emily Carter",
            authorAvatarUrl: "/avatars/05.png",
            text: "Thank you for the update!",
            timestamp: "2024-08-24T09:15:00Z",
            isInternal: false,
        }
    ]
  },
];
